export const LOGIN_ROUTE = '/login'
export const ABOUT_ROUTE = '/about'
export const NEWS_ROUTE = '/'
export const ACHIEVEMENTS_ROUTE = '/achievements'
export const STATS_ROUTE = '/stats'
export const WIDGETS_ROUTE = '/widgets'
export const CONTACT_ROUTE = '/contact' 
